### ISSUE TITLE
Data Version Control

### ISSUE THREAD

**Issue by wcheema-synsor** [synsorai/MOPS#11]
**Context**
We are trying to set up our own datasets for anomaly detection (image datasets) very soon. Most likely multiple datasets for different products and containing a large number of images (around 500) and hosted on the cloud. We want to explore what data version control could do for us. 

**Task**
1. Get some basic knowledge about Data Version Control (DVC) and how it fits with the CML pipeline. 
2. What tools are out there for DVC and their advantages/disadvantages. Tools that connect easily with cloud services should be preferred.
3. How can DVC help us in our use case. We have a deep learning pipeline (anomaly detection) with multiple datasets hosted on the cloud coming soon.

**Goal of the exploration**
The goal would be a one page document (and possibly) a small presentation that covers the 3 things mentioned above so we can decide if we should fit DVC into our workflow, how to do it and what benefits we could get from it.

**Comment by Masmoudi-synsor** [comment]
[https://drive.google.com/file/d/19rhCNuSmw-u8LQTY5ns9LpkCpzXPa0v5/view?usp=sharing](url)

**Comment by Masmoudi-synsor** [comment]
https://drive.google.com/file/d/19rhCNuSmw-u8LQTY5ns9LpkCpzXPa0v5/view?usp=sharing
